api/uisvc/test/basic_test.go, handlers/handler.go, testutil/testservers/servers.go
Currently, there was an assumption in the tests that allowed servers to
never create the no_auth user based on its token value. This would allow
the services to boot, but have no legitimate user information to use.
This fixes it and removes a hack in the test that obscured the bug. yay.
=> Fix no_auth user creation

api/uisvc/processors/token.go, api/uisvc/test/basic_test.go, config/auth.go, testutil/testservers/servers.go
closes #30
This resolves a loophole in no_auth mode where tokens could be retrieved
and deleted by anyone.
=> Fix tokens in no_auth mode

Makefile
requires the push of tinyci/redoc-cli to the hub for upgrading redoc
=> Makefile: fix swagger documentation generator

.config/services.yaml.example, api/assetsvc/processors/log.go, cmd/assetsvc/main.go, testutil/testservers/servers.go
This is an artifact of an earlier era. This parameter is now tweakable
via the `logs_root_path` parameter of the `services` settings.
closes #46 
=> Parameterize the assetsvc logs path

cmd/tinycli/main.go, model/queue.go
To be consistent with other UI implementations.
=> tinycli: instead of reporting ".", it now reports "*root*"

handlers/handler.go
=> Return an error instead of trying to redirect on oauth2 scope issues

Makefile
The first time, otherwise it'll break.
=> Makefile: build the dist image before trying to clean the dist

cmd/assetsvc/main.go, cmd/cancelbot/main.go, cmd/datasvc/main.go, cmd/hooksvc/main.go, cmd/logsvc/main.go, cmd/queuesvc/main.go, cmd/tinycli/main.go, errors/error.go
This unifies error reporting after the program is ready to exit inside
the errors library.
=> cmd,errors: handle exit more generically and predictably

Makefile, api/queuesvc/processors/processor.go, testutil/cmd/tinyci-fixturegen/main.go
The tinyci-fixturegen program generates randomized dummy data suitable
for use in UI or other situations such as fuzz-style testing or
behavioral testing on random data in general (e.g., integration
testing).
It has several tweakables and generates everything from users to the
individual runs.
Future plans include log uploads and queue states, which I didn't feel
were necessary for the first spike.
This also includes a small patch to create a `demo-shell` Makefile task
that allows you to jump into a `make demo` session for extra work.
=> Fixture generator that talks through normal routes 

cmd/assetsvc/main.go, cmd/datasvc/main.go, cmd/logsvc/main.go, cmd/queuesvc/main.go, go.mod, go.sum, handlers/handler.go, testutil/testservers/servers.go, utils/tracer.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/LICENSE, vendor/github.com/grpc-ecosystem/grpc-opentracing/PATENTS, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/README.md, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/errors.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/options.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/package.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/shared.go, vendor/modules.txt
This adds the finished channel pattern to the grpc services as well.
It also integrates server-side opentracing by way of the jaegertracing
client. Client support still needs to be integrated.
=>  Support for finished channels, grpc tracing

ci-gen/grpc/handler/handler.go, cmd/assetsvc/main.go, cmd/datasvc/main.go, cmd/logsvc/main.go, cmd/queuesvc/main.go
This was not actually gated in the grpc services, so it was causing some
trouble.
=> Fix enable/disable tracing in ci-gen/grpc handlers

.gitmodules, LICENSE.md, box-release.rb
This doesn't get installed in the release image ATM; caused some issues
talking to github.
=> box-release.rb: install ca-certificates

api/datasvc/test/basic_test.go, api/queuesvc/processors/processor.go, api/queuesvc/processors/routes.go, api/queuesvc/test/basic_test.go, api/queuesvc/test/setup_test.go, api/uisvc/test/basic_test.go, testutil/cmd/tinyci-fixturegen/main.go, testutil/testclients/datasvc.go, testutil/testclients/queuesvc.go
This change is a little weird. Basically, if you take a parent, fork it,
and then add the *fork* to tinyCI, it would break submitting because it
was trying to resolve the parent, which may not belong to the user.
It was behaving properly, but in the event the fork was submitted
manually, it should behave like an added repository.
There's probably a few bugs that I haven't caught yet on this feature. I
hope to suss them out soon.
I also added liberal logging to the queue submission in a vain attempt
to figure out why my mocks weren't working, but they seem to add a
little useful tracing data so I'm keeping them for now until real
tracing arrives for real.
=> In the event a submitted branch is a fork AND added to the db, process it directly.

cmd/cancelbot/main.go, cmd/tinyci-adduser/main.go
This also contains a small fix for cancelbot's descriptive text which I noticed while working on this.
If given a personal access token, it will use that to derive the
username and assign the token. It will also populate the login token in
the DB and return it so that you can use token auth to access this
account.
=>  cmd/tinyci-adduser: new tool to add users at the commandline

model/task_runs.go, model/task_runs_test.go
This was displaying in the insert order otherwise.
=> order runs for a given task by run id descending

migrations/tinyci/1.sql, model/task.go
The AfterFind hook was reaping a separate run count for each row
selected, instead of aggregating the result in a single query. This was
unsurprisingly expensive.
=> Improve task list performance in UI

cmd/tinycli/main.go
The warnings were spammy for someone who had configured TLS with a
certificate chain in the trust store for no good reason. Now, for the
manually-programmed case it will just error from the cert load.
=> cmd/tinycli/main.go: remove warning and correct predicate

model/submission.go, model/submission_test.go
This was because the run was already finished for some reason. Now we're
just skipping errors.
closes #121
=> Fix situations where tasks could not be canceled via submission

api/assetsvc/setup_test.go, api/assetsvc/testserver.go, api/datasvc/testserver.go, api/logsvc/setup_test.go, api/logsvc/testserver.go, api/queuesvc/testserver.go, api/uisvc/restapi/setup_test.go, api/uisvc/restapi/testserver.go, cmd/assetsvc/main.go, cmd/cancelbot/main.go, cmd/datasvc/main.go, cmd/logsvc/main.go, cmd/queuesvc/main.go, cmd/reposvc/github-reposvc/main.go, cmd/tinyci-adduser/main.go, config/routes.go, config/service.go, testutil/testclients/datasvc.go, testutil/testclients/queuesvc.go
This adds a basic static route mapping atop the configuration already
provided; this allows us to easier manipulate defaults and manage port
maps as the service count grows.
=> Add route mapping

ci-gen/Makefile, ci-gen/box.rb, ci-gen/task.yml
This makes it in sync with our ci-agents image:
* golang 1.13
* ubuntu 19.04 disco
=> Upgrade ci-gen image

model/submission.go
Fixes ticket recording in database.
=> Repopulate ticket id in submission conversion

api/queuesvc/basic_test.go, api/queuesvc/processor.go, api/queuesvc/routes.go, api/uisvc/restapi/basic_test.go, api/uisvc/restapi/repository.go, clients/github/github.go, cmd/tinyci-adduser/main.go, handlers/handler.go, mocks/github/mock.go, model/cancel_test.go, model/run.go, model/submission_test.go, testutil/testclients/queuesvc.go
Long time coming. Now, github API calls will appropriately terminate
early when the connection is closed on the HTTP end.
=> Make github client use contexts

clients/github/github.go, clients/github/task.yml, config/service.go
This allows certain workflows with integration tests we want to do, but
ultimately just disallows API requests for certain actions based on a
setting called `readonly_client`, which may be present in the
configuration. If supplied, things like status updates, hook settings
and other "write to github" operations will be nullified, allowing the
system to continue to work otherwise.
=> Github readonly client mode

docker-compose.yml
will eventually run the machine out of ram. Software.
=> Limit jaeger traces in docker compose

Makefile, api/datasvc/basic_test.go, api/datasvc/queue.go, api/datasvc/ref.go, api/queuesvc/basic_test.go, api/queuesvc/setup_test.go, api/queuesvc/submission.go, api/queuesvc/task_picker.go, api/uisvc/restapi/basic_test.go, api/uisvc/restapi/testserver.go, config/oauth.go, config/service.go, go.mod, go.sum, model/ref.go, testutil/testclients/queuesvc.go
Right now the solution is to hardcode `heads/master` in a few spots
which was inadequate.
Luckily for us, github renamed the API too (to something more
inclusive), default_branch instead of master_branch contains the default
branch in the API responses now.
I also took the time to clean up some very ugly submission logic.
=> Remove explicit master branch references in code, support testing off default branch github API

Makefile
So resources are automatically cleaned up before starting a new demo
instance. Was causing trouble.
=> Makefile: hook the stop-demo task into demo

Makefile, cmd/tinyci/main.go, cmdlib/cmdlib.go, go.mod
This now works as a single command:
`tinyci launch`
and runs the entire suite.
Only postgres and the UI are required to operate the CI after launching
this command, but the hooksvc is still launched independently. This will
be fixed soon.
=> `tinyci launch`: Multi-launch in single binary

.config/Caddyfile, .config/runner.yaml, .gitignore, docker-compose.yml
This enables the `make demo` task and associated `docker-compose` tooling to run the overlay runner alongside the other services so that testing can occur.
=> Boot runner in container

.gitignore, .golangci.yml, Makefile
staticcheck seems to have a bug detecting interface nils in my janky
error handling code. Need to talk to dominikh.
=> Upgrade and correct golangci-lint installation; remove staticcheck

clients/tinyci/client.go, cmd/tinycli/main.go
Using different calls and a smarter method. Fully compatible with 0.3.0
too.
closes #224
=> Improve the submission/task listings RTT by a great deal of time

api/handlers/grpc/handler.go, api/services/grpc/datasvc/setup_test.go, api/services/grpc/logsvc/basic_test.go, api/services/grpc/logsvc/server.go, api/services/grpc/logsvc/setup_test.go, api/services/grpc/logsvc/submit.go, api/services/grpc/logsvc/testserver.go, api/services/grpc/queuesvc/setup_test.go, api/services/openapi/uisvc/setup_test.go, clients/log/log.go, cmd/tinyci/servers.go, config/service.go
This fixes the following issues:
- logging level was not selectable
- in many instances, logs would be shipped twice; once on the service,
once to the remote
- logging filtering was not working properly
=> Focus on logging

api/services/grpc/datasvc/queue.go, api/services/grpc/datasvc/setup_test.go, api/services/grpc/datasvc/testserver.go, api/services/grpc/queuesvc/setup_test.go, api/services/openapi/uisvc/basic_test.go, api/services/openapi/uisvc/setup_test.go, db/protoconv/map.go
This fixes:
- Data races in uisvc tests
- DB close issues
- Improper use of mock github client in a few situations.
=> Fix test races, db close issues
