tinyci/ci-agents

api/uisvc/processors/run.go
api/uisvc/test/basic_test.go

Disallow cancels in no_modify mode

---

model/repository.go

This adds escaping to search queries so that SQL meta characters for LIKE stanzas cannot be used.
It's probably not perfect.

Handle escaping in search queries

---

api/datasvc/processors/run.go
model/run.go

I really need to write more tests

Remove owners entirely from codebase

---

Makefile
README.md

Rewrite URLs to use tinyci.org

---

api/uisvc/test/basic_test.go
clients/tinyci/client.go
gen/client/uisvc/models/repository_list.go
gen/client/uisvc/models/run.go
gen/client/uisvc/models/run_list.go
gen/client/uisvc/models/task_list.go
gen/svc/uisvc/models/repository_list.go
gen/svc/uisvc/models/run.go
gen/svc/uisvc/models/run_list.go
gen/svc/uisvc/models/task_list.go
gen/svc/uisvc/restapi/embedded_spec.go
model/repository.go
swagger/models.yml

closes #52. Contains a few extra bits to test things better.

Fix hook secret

---

cmd/tinycli/main.go

This allows you to specify the `-c` flag before any commands, or set
`TINYCLI_CONFIG` to change the configuration on the fly. Might be nice
for a few of us who use different servers.

tinycli: support many configurations without moving files

---

Makefile

Makefile: Remove requirement for react container for grpc-docs

---

types/crypto.go

Our GCM usage requires no additional data segment, making it an AE
encrypter not an AEAD encrypter (as the documentation would imply). This
is perfectly normal behavior within this system. I checked my
assumptions about carrying the nonce/iv with with the ciphertext; this
seems to be a common strategy so I'm on solid ground there.
This should be a little better than using the CFB cipher suite.

types/crypto.go: convert to use GCM from CFB.

---

api/queuesvc/test/basic_test.go

fix timeout in queuesvc tests to be absurdly long

---

cmd/tinyci-adduser/main.go

Small refactors for the new adduser utility

---

.gitignore
model/basic_test.go
model/cancel_test.go
model/oauth.go
model/oauth_test.go
model/protoconv.go
model/protoconv_test.go
model/queue.go
model/queue_test.go
model/ref_test.go
model/repository_test.go
model/run.go
model/user.go
model/utils_for_test.go
testutil/utils.go

More to come; just checkpointing for now.

Lots of model tests due to coverage testing

---

handlers/handler.go

Clear session cookies when they're bad.

---

model/task.yml

Break up model tests further

---

Makefile

Makefile: fix compiles to include api dir and remove ci-gen dir

---

model/user.go

Fix a security hole that would be present in submission ID work

---

api/uisvc/restapi/configure_uisvc.go

Add count route to uisvc

---

model/submission.go
model/task.go

Required refactoring the count aggregator for run/task relationships.

Add run counts to task lists returned for submissions

---

api/uisvc/models/model_submission.go
api/uisvc/models/model_submission_list.go
api/uisvc/restapi/embedded_spec.go
ci-gen/gen/client/uisvc/models/model_submission.go
ci-gen/gen/client/uisvc/models/model_submission_list.go
ci-gen/swagger/models.yml
model/submission.go

Make started_at and finished_at nullable in submissions

---

cmd/assetsvc/main.go
cmd/datasvc/main.go
cmd/logsvc/main.go
cmd/queuesvc/main.go
cmd/reposvc/github-reposvc/main.go
cmdlib/cmdlib.go

This allows us (and others) to more easily create compatible services.

Refactoring of cmd dir; command-line utilities and service management

---

Makefile

Upgrade release materials to golang 1.13

---

clients/tinyci/client.go
cmd/tinycli/main.go

Submissions support for tinycli

---

api/assetsvc/task.yml
api/datasvc/task.yml
api/logsvc/task.yml
api/queuesvc/task.yml
api/uisvc/task.yml
clients/jsonbuffer/task.yml
clients/retry/task.yml
clients/utils/task.yml
errors/task.yml
model/task.yml
types/task.yml
utils/task.yml

Set go test -mod=vendor for all tasks

---

api/queuesvc/processor.go

sort task list before submitting queue items

---

Makefile
entrypoint.sh

Some small things I noticed tonight while working on the project.

Small bits and bites

---

api/assetsvc/task.yml
api/datasvc/task.yml
api/logsvc/task.yml
api/queuesvc/task.yml
api/uisvc/task.yml
clients/jsonbuffer/task.yml
clients/retry/task.yml
clients/utils/task.yml
task.yml

Update base image to 09.30

---

Makefile
errors/task.yml
model/task.yml
types/task.yml
utils/task.yml

Update more task.ymls

---

api/uisvc/restapi/configure_uisvc.go

Add route for uisvc (oops)

---

ci-gen/swagger/templates/server/parameter.gotmpl

No code currently uses this functionality

Guard against future code gen issues by limiting the ReadAll call

---

model/user_test.go

Signed-off-by: roz3x <oroz3x@gmail.com>

added test for user token

---

utils/repository.go
utils/utils_test.go

Signed-off-by: roz3x <oroz3x@gmail.com>

added test cases for OwnerRepo function

---

api/queuesvc/routes.go

Fix a null deref setting the log values after the errors patch

---

ci-gen/grpc/handler/handler.go

Cleanup some of the grpc handler; also use GracefulStop() to mitigate issues with submissions

---

api/queuesvc/submission.go

Fix issues with branch creation leading to ugly refs on the UI

---

Makefile
README.md
docker-compose.yml

Use/support docker-compose in demo setup

---

docker-compose.yml

Mute jaeger debug logging

---

Makefile

properly execute the docker-compose shell

---

Makefile
api/assetsvc/task.yml
api/datasvc/task.yml
api/logsvc/task.yml
api/queuesvc/task.yml
api/uisvc/task.yml
clients/jsonbuffer/task.yml
clients/retry/task.yml
clients/utils/task.yml
entrypoint.sh
errors/task.yml
model/task.yml
task.yml
types/task.yml
utils/task.yml

Update to use the new image

---

errors/errors_test.go

Sanity test to help me sleep at night.

Check errors package to ensure nils come out as nils

---

api/hooksvc/incoming.go

Fix hooksvc to not write to http ResponseWriters in goroutines

---

.config/Caddyfile
box-builds/box.rb
entrypoint.sh

This leads to some interesting things with the auto tls stuff; but not
today.

Use caddy server in demo

---

go.mod
go.sum

Upgrade existing dependencies (before bringing in new ones)

---

api/assetsvc/task.yml
api/datasvc/task.yml
api/logsvc/task.yml
api/queuesvc/task.yml
api/uisvc/task.yml
clients/jsonbuffer/task.yml
clients/retry/task.yml
clients/utils/task.yml
dockerfiles/Dockerfile
errors/task.yml
go.mod
go.sum
model/task.yml
task.yml
types/task.yml
utils/task.yml

Upgrade test container images

---

.golangci.yml

Re-enable staticcheck

---

Makefile

Add a build cache from a docker volume; for golang building goodness

---

api/services/openapi/uisvc/handler.go
config/service.go

Allow for CORS origin settings.

---

api/handlers/grpc/handler.go
cmd/tinyci/servers.go
cmdlib/cmdlib.go
db/user.go

Restore much needed logging functionality

---

api/handlers/grpc/handler.go
api/services/grpc/logsvc/dispatch.go
api/services/openapi/uisvc/handler.go

make logging better

---

api/services/grpc/datasvc/queue.go
db/run.go
db/task.go

more fixes.
